### PR TITLE
Add Touch Bar Support

### PR DESCRIPTION
**Pull request by CaptainYukinoshitaHachiman**
Added Touch Bar Support due to #4.

Suggestions are written in the project using `#warning()`

The Control Strip is configured using the method mentioned by @AutinMitra in the issue, thanks!

### CODE REVIEW

**Comment by AutinMitra** [comment]
The pull request does add the necessary code to get everything working, but is missing a few things to make it work (if my setup is not broken). First of all, the bridging header seems to not exist within the workspace (but rather as a file - could be my mistake). Second of all, the private framework has not been imported to the project (/System/Library/PrivateFrameworks/DFRFoundation.framework). Also, it seems that you have given the slider a label which I believe was intended to be an identifier ("io.github.apollozhu.Dynamic.AutoAdjustThreshold"). Swift is kinda new to me, so what I have said could have been my mistake.

**Comment by CaptainYukinoshitaHachiman** [comment]
Thanks for your advice!

Maybe I should change the localization key to something like “localization.settings.threshold”.

And the framework should be correctly linked since it works on my Mac, I’ll check it later (I have to do my homework now :-( )

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CaptainYukinoshitaHachiman** [comment]
It should work well now, could you please have a check? @ApolloZhu @AutinMitra

**Comment by ApolloZhu** [comment]
Sorry for coming back to this so late, and @CaptainYukinoshitaHachiman and @AutinMitra , thank you so much for your time and effort! I can't imaging myself doing all these.

> I don't know where this @houndci-bot is coming from, but that's okay.

**Comment by CaptainYukinoshitaHachiman** [comment]
Cool, you've made the code much more elegant. Can we merge this PR now?

**Pull request merged**
